# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.224.3/containers/cpp/.devcontainer/base.Dockerfile

# [Choice] Debian / Ubuntu version (use Debian 11, Ubuntu 18.04/21.04 on local arm64/Apple Silicon): debian-11, debian-10, ubuntu-21.04, ubuntu-20.04, ubuntu-18.04
#ARG VARIANT="bullseye"
#FROM sres.web.boeing.com:5000/vscode/devcontainers/cpp:0-${VARIANT}
FROM registry.web.boeing.com/container/boeing-images/stack/ubi8-node16

RUN adduser -G wheel -u 1000 -g 1000 -d vscode
RUN mkdir /root
RUN mkdir -p /home/vscode

ARG SRES_UBI_ID=notset
ARG SRES_UBI_TOKEN=notset
RUN echo ${SRES_UBI_ID} > /etc/yum/vars/sresubiid && echo ${SRES_UBI_TOKEN} > /etc/yum/vars/sresubitoken

RUN yum -y install cmake git sudo
# [Optional] Install CMake version different from what base image has already installed. 
# CMake reinstall choices: none, 3.21.5, 3.22.2, or versions from https://cmake.org/download/
# ARG REINSTALL_CMAKE_VERSION_FROM_SOURCE="none"

# # Optionally install the cmake for vcpkg
# COPY ./reinstall-cmake.sh /tmp/
# RUN if [ "${REINSTALL_CMAKE_VERSION_FROM_SOURCE}" != "none" ]; then \
#         chmod +x /tmp/reinstall-cmake.sh && /tmp/reinstall-cmake.sh ${REINSTALL_CMAKE_VERSION_FROM_SOURCE}; \
#     fi \
#     && rm -f /tmp/reinstall-cmake.sh

# [Optional] Uncomment this section to install additional vcpkg ports.
# RUN su vscode -c "${VCPKG_ROOT}/vcpkg install <your-port-name-here>"

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends inotify-tools pip

# RUN pip install -U platformio